version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - x-app-network

  mongo-db:
    image: mongo:6
    container_name: primary-db
    ports:
      - "27018:27017"
    volumes: 
      - user-data:/data/db
    networks:
      - x-app-network
     
  redis-db:
    image: redis:7
    container_name: cache-db
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - notification-data:/data
    networks:
      - x-app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - x-app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - x-app-network

  server-nestjs:
    image: node:20
    container_name: server-nestjs
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo-db:27017/yourdb
      - REDIS_URL=redis://redis-db:6379
    networks:
      - x-app-network
    depends_on:
      - mongo-db
      - redis-db

  nextjs-client:
    image: node:20
    container_name: nextjs-client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - x-app-network
    depends_on:
      - server-nestjs

networks:
  x-app-network:
    driver: bridge

volumes:
  user-data:
  notification-data:
  esdata: